#!/usr/bin/php
<?

include dirname(__FILE__) . "/../fammel.php";

require_once dirname(__FILE__) . '/../lib/PHPSpec/Framework.php';
require dirname(__FILE__) . '/../lib/PHPSpec/Console/Command.php';

exit(0);

?>
